"""
Seed 50 synthetic payment records across 6 failure categories.
Each record has a hidden_recovery_outcome used by the simulator.
Distribution is designed to produce ~30-35% AI recovery rate.
"""
from datetime import datetime, timedelta

_now = datetime.now()


def h(n):
    """Return datetime n hours ago."""
    return _now - timedelta(hours=n)


PAYMENTS_SEED = [
    # ── SOFT DECLINE (12) ────────────────────────────────────────────────
    {
        "payment_id": "pay_SD001", "customer_id": "cust_101", "customer_name": "Rahul Sharma",
        "amount": 4999.0, "currency": "INR", "payment_method": "card",
        "failure_category": "soft_decline", "failure_code": "ISSUER_TIMEOUT",
        "failure_message": "Issuer did not respond in time. Retry recommended.",
        "attempt_count": 1, "customer_locale": "hi-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(12), "last_attempt_at": h(10),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_SD002", "customer_id": "cust_102", "customer_name": "Priya Mehta",
        "amount": 1299.0, "currency": "INR", "payment_method": "upi",
        "failure_category": "soft_decline", "failure_code": "BANK_TIMEOUT",
        "failure_message": "Bank server timeout. Transient error.",
        "attempt_count": 1, "customer_locale": "en-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(8), "last_attempt_at": h(7),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_SD003", "customer_id": "cust_103", "customer_name": "Amit Verma",
        "amount": 8500.0, "currency": "INR", "payment_method": "netbanking",
        "failure_category": "soft_decline", "failure_code": "ISSUER_TIMEOUT",
        "failure_message": "Issuer timeout on netbanking transaction.",
        "attempt_count": 2, "customer_locale": "en-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(20), "last_attempt_at": h(8),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_SD004", "customer_id": "cust_104", "customer_name": "Sunita Patel",
        "amount": 2200.0, "currency": "INR", "payment_method": "card",
        "failure_category": "soft_decline", "failure_code": "TRANSIENT_BANK_ERROR",
        "failure_message": "Transient bank error. Try after some time.",
        "attempt_count": 1, "customer_locale": "gu-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(6), "last_attempt_at": h(6),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_SD005", "customer_id": "cust_105", "customer_name": "Deepak Kumar",
        "amount": 15000.0, "currency": "INR", "payment_method": "card",
        "failure_category": "soft_decline", "failure_code": "ISSUER_TIMEOUT",
        "failure_message": "Issuer timeout. High-value transaction.",
        "attempt_count": 1, "customer_locale": "en-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(14), "last_attempt_at": h(10),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_SD006", "customer_id": "cust_106", "customer_name": "Kavita Singh",
        "amount": 32000.0, "currency": "INR", "payment_method": "card",
        "failure_category": "soft_decline", "failure_code": "TRANSIENT_BANK_ERROR",
        "failure_message": "Transient error on high-value transaction.",
        "attempt_count": 1, "customer_locale": "en-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(10), "last_attempt_at": h(8),
        "hidden_recovery_outcome": "escalated",  # amount > 25000
    },
    {
        "payment_id": "pay_SD007", "customer_id": "cust_107", "customer_name": "Rajesh Nair",
        "amount": 3600.0, "currency": "INR", "payment_method": "upi",
        "failure_category": "soft_decline", "failure_code": "BANK_TIMEOUT",
        "failure_message": "Bank timeout. Max retries exhausted.",
        "attempt_count": 3, "customer_locale": "ml-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(30), "last_attempt_at": h(7),
        "hidden_recovery_outcome": "not_recovered",  # max retries
    },
    {
        "payment_id": "pay_SD008", "customer_id": "cust_108", "customer_name": "Meena Rao",
        "amount": 560.0, "currency": "INR", "payment_method": "card",
        "failure_category": "soft_decline", "failure_code": "ISSUER_TIMEOUT",
        "failure_message": "Issuer timeout. Customer opted out.",
        "attempt_count": 1, "customer_locale": "te-IN", "consent_for_voice": False, "opted_out": True,
        "created_at": h(5), "last_attempt_at": h(5),
        "hidden_recovery_outcome": "not_recovered",  # opted out
    },
    {
        "payment_id": "pay_SD009", "customer_id": "cust_109", "customer_name": "Vikram Bose",
        "amount": 7200.0, "currency": "INR", "payment_method": "netbanking",
        "failure_category": "soft_decline", "failure_code": "BANK_TIMEOUT",
        "failure_message": "Netbanking timeout. Ambiguous failure pattern.",
        "attempt_count": 1, "customer_locale": "bn-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(9), "last_attempt_at": h(9),
        "hidden_recovery_outcome": "not_recovered",
    },
    {
        "payment_id": "pay_SD010", "customer_id": "cust_110", "customer_name": "Ananya Das",
        "amount": 1800.0, "currency": "INR", "payment_method": "upi",
        "failure_category": "soft_decline", "failure_code": "TRANSIENT_BANK_ERROR",
        "failure_message": "Transient UPI error. Retry eligible.",
        "attempt_count": 2, "customer_locale": "en-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(15), "last_attempt_at": h(8),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_SD011", "customer_id": "cust_111", "customer_name": "Suresh Iyer",
        "amount": 4100.0, "currency": "INR", "payment_method": "card",
        "failure_category": "soft_decline", "failure_code": "ISSUER_TIMEOUT",
        "failure_message": "Card issuer timeout.",
        "attempt_count": 1, "customer_locale": "ta-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(11), "last_attempt_at": h(7),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_SD012", "customer_id": "cust_112", "customer_name": "Pooja Gupta",
        "amount": 999.0, "currency": "INR", "payment_method": "card",
        "failure_category": "soft_decline", "failure_code": "TRANSIENT_BANK_ERROR",
        "failure_message": "Transient error. Retry should succeed.",
        "attempt_count": 1, "customer_locale": "hi-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(7), "last_attempt_at": h(7),
        "hidden_recovery_outcome": "recovered",
    },

    # ── INSUFFICIENT FUNDS (9) ───────────────────────────────────────────
    {
        "payment_id": "pay_IF001", "customer_id": "cust_201", "customer_name": "Arjun Kapoor",
        "amount": 2499.0, "currency": "INR", "payment_method": "card",
        "failure_category": "insufficient_funds", "failure_code": "INSUFFICIENT_BALANCE",
        "failure_message": "Card declined due to insufficient balance.",
        "attempt_count": 1, "customer_locale": "hi-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(6), "last_attempt_at": h(6),
        "hidden_recovery_outcome": "needs_customer_action",
    },
    {
        "payment_id": "pay_IF002", "customer_id": "cust_202", "customer_name": "Nisha Reddy",
        "amount": 5000.0, "currency": "INR", "payment_method": "card",
        "failure_category": "insufficient_funds", "failure_code": "INSUFFICIENT_BALANCE",
        "failure_message": "Insufficient balance. Payment link sent.",
        "attempt_count": 1, "customer_locale": "te-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(10), "last_attempt_at": h(10),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_IF003", "customer_id": "cust_203", "customer_name": "Kiran Shah",
        "amount": 1500.0, "currency": "INR", "payment_method": "upi",
        "failure_category": "insufficient_funds", "failure_code": "LOW_BALANCE",
        "failure_message": "UPI payment failed due to low balance.",
        "attempt_count": 2, "customer_locale": "gu-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(18), "last_attempt_at": h(10),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_IF004", "customer_id": "cust_204", "customer_name": "Rohit Joshi",
        "amount": 3200.0, "currency": "INR", "payment_method": "card",
        "failure_category": "insufficient_funds", "failure_code": "INSUFFICIENT_BALANCE",
        "failure_message": "Card balance insufficient. Customer opted out.",
        "attempt_count": 1, "customer_locale": "mr-IN", "consent_for_voice": False, "opted_out": True,
        "created_at": h(8), "last_attempt_at": h(8),
        "hidden_recovery_outcome": "not_recovered",  # opted out
    },
    {
        "payment_id": "pay_IF005", "customer_id": "cust_205", "customer_name": "Shalini Mishra",
        "amount": 28500.0, "currency": "INR", "payment_method": "card",
        "failure_category": "insufficient_funds", "failure_code": "INSUFFICIENT_BALANCE",
        "failure_message": "High-value insufficient funds transaction.",
        "attempt_count": 1, "customer_locale": "hi-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(12), "last_attempt_at": h(12),
        "hidden_recovery_outcome": "escalated",  # > 25000
    },
    {
        "payment_id": "pay_IF006", "customer_id": "cust_206", "customer_name": "Manish Tiwari",
        "amount": 750.0, "currency": "INR", "payment_method": "upi",
        "failure_category": "insufficient_funds", "failure_code": "LOW_BALANCE",
        "failure_message": "Low balance on UPI account.",
        "attempt_count": 1, "customer_locale": "hi-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(4), "last_attempt_at": h(4),
        "hidden_recovery_outcome": "not_recovered",
    },
    {
        "payment_id": "pay_IF007", "customer_id": "cust_207", "customer_name": "Rekha Pillai",
        "amount": 4200.0, "currency": "INR", "payment_method": "card",
        "failure_category": "insufficient_funds", "failure_code": "INSUFFICIENT_BALANCE",
        "failure_message": "Insufficient balance on credit card.",
        "attempt_count": 1, "customer_locale": "ml-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(16), "last_attempt_at": h(14),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_IF008", "customer_id": "cust_208", "customer_name": "Gaurav Saxena",
        "amount": 1100.0, "currency": "INR", "payment_method": "card",
        "failure_category": "insufficient_funds", "failure_code": "INSUFFICIENT_BALANCE",
        "failure_message": "Balance too low for transaction.",
        "attempt_count": 1, "customer_locale": "en-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(20), "last_attempt_at": h(15),
        "hidden_recovery_outcome": "not_recovered",
    },
    {
        "payment_id": "pay_IF009", "customer_id": "cust_209", "customer_name": "Preethi Nair",
        "amount": 6800.0, "currency": "INR", "payment_method": "netbanking",
        "failure_category": "insufficient_funds", "failure_code": "LOW_BALANCE",
        "failure_message": "Insufficient funds in bank account.",
        "attempt_count": 1, "customer_locale": "ta-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(9), "last_attempt_at": h(9),
        "hidden_recovery_outcome": "needs_customer_action",
    },

    # ── HARD DECLINE (8) ─────────────────────────────────────────────────
    {
        "payment_id": "pay_HD001", "customer_id": "cust_301", "customer_name": "Vikash Agarwal",
        "amount": 3000.0, "currency": "INR", "payment_method": "card",
        "failure_category": "hard_decline", "failure_code": "CARD_BLOCKED",
        "failure_message": "Card is blocked. Contact issuing bank.",
        "attempt_count": 1, "customer_locale": "en-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(5), "last_attempt_at": h(5),
        "hidden_recovery_outcome": "blocked",
    },
    {
        "payment_id": "pay_HD002", "customer_id": "cust_302", "customer_name": "Divya Chopra",
        "amount": 9999.0, "currency": "INR", "payment_method": "card",
        "failure_category": "hard_decline", "failure_code": "SUSPECTED_FRAUD",
        "failure_message": "Transaction suspected as fraudulent. Card blocked.",
        "attempt_count": 1, "customer_locale": "hi-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(3), "last_attempt_at": h(3),
        "hidden_recovery_outcome": "blocked",
    },
    {
        "payment_id": "pay_HD003", "customer_id": "cust_303", "customer_name": "Ravi Shankar",
        "amount": 1800.0, "currency": "INR", "payment_method": "card",
        "failure_category": "hard_decline", "failure_code": "INVALID_CARD",
        "failure_message": "Card number is invalid.",
        "attempt_count": 1, "customer_locale": "kn-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(7), "last_attempt_at": h(7),
        "hidden_recovery_outcome": "blocked",
    },
    {
        "payment_id": "pay_HD004", "customer_id": "cust_304", "customer_name": "Shilpa Jain",
        "amount": 2750.0, "currency": "INR", "payment_method": "card",
        "failure_category": "hard_decline", "failure_code": "CARD_BLOCKED",
        "failure_message": "Card blocked by issuer.",
        "attempt_count": 2, "customer_locale": "hi-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(20), "last_attempt_at": h(14),
        "hidden_recovery_outcome": "blocked",
    },
    {
        "payment_id": "pay_HD005", "customer_id": "cust_305", "customer_name": "Naresh Menon",
        "amount": 5500.0, "currency": "INR", "payment_method": "card",
        "failure_category": "hard_decline", "failure_code": "SUSPECTED_FRAUD",
        "failure_message": "Fraud risk flag raised by issuer.",
        "attempt_count": 1, "customer_locale": "ml-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(6), "last_attempt_at": h(6),
        "hidden_recovery_outcome": "blocked",
    },
    {
        "payment_id": "pay_HD006", "customer_id": "cust_306", "customer_name": "Sangeeta Roy",
        "amount": 12000.0, "currency": "INR", "payment_method": "card",
        "failure_category": "hard_decline", "failure_code": "CARD_BLOCKED",
        "failure_message": "Card permanently blocked.",
        "attempt_count": 1, "customer_locale": "bn-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(11), "last_attempt_at": h(11),
        "hidden_recovery_outcome": "blocked",
    },
    {
        "payment_id": "pay_HD007", "customer_id": "cust_307", "customer_name": "Tarun Chauhan",
        "amount": 4300.0, "currency": "INR", "payment_method": "card",
        "failure_category": "hard_decline", "failure_code": "INVALID_CARD",
        "failure_message": "Invalid card details.",
        "attempt_count": 1, "customer_locale": "en-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(8), "last_attempt_at": h(8),
        "hidden_recovery_outcome": "blocked",
    },
    {
        "payment_id": "pay_HD008", "customer_id": "cust_308", "customer_name": "Mala Trivedi",
        "amount": 8800.0, "currency": "INR", "payment_method": "card",
        "failure_category": "hard_decline", "failure_code": "SUSPECTED_FRAUD",
        "failure_message": "Transaction blocked due to fraud detection.",
        "attempt_count": 1, "customer_locale": "gu-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(4), "last_attempt_at": h(4),
        "hidden_recovery_outcome": "blocked",
    },

    # ── AUTHENTICATION FAILED (9) ────────────────────────────────────────
    {
        "payment_id": "pay_AF001", "customer_id": "cust_401", "customer_name": "Ritu Agrawal",
        "amount": 2499.0, "currency": "INR", "payment_method": "card",
        "failure_category": "authentication_failed", "failure_code": "3DS_FAILED",
        "failure_message": "3D Secure authentication failed.",
        "attempt_count": 1, "customer_locale": "hi-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(8), "last_attempt_at": h(8),
        "hidden_recovery_outcome": "needs_customer_action",
    },
    {
        "payment_id": "pay_AF002", "customer_id": "cust_402", "customer_name": "Ankit Srivastava",
        "amount": 3800.0, "currency": "INR", "payment_method": "upi",
        "failure_category": "authentication_failed", "failure_code": "UPI_PIN_FAILED",
        "failure_message": "UPI PIN authentication failed.",
        "attempt_count": 1, "customer_locale": "hi-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(6), "last_attempt_at": h(6),
        "hidden_recovery_outcome": "needs_customer_action",
    },
    {
        "payment_id": "pay_AF003", "customer_id": "cust_403", "customer_name": "Lakshmi Venkat",
        "amount": 1200.0, "currency": "INR", "payment_method": "card",
        "failure_category": "authentication_failed", "failure_code": "OTP_FAILED",
        "failure_message": "OTP expired or incorrect.",
        "attempt_count": 2, "customer_locale": "te-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(14), "last_attempt_at": h(8),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_AF004", "customer_id": "cust_404", "customer_name": "Shyam Pandey",
        "amount": 5600.0, "currency": "INR", "payment_method": "card",
        "failure_category": "authentication_failed", "failure_code": "3DS_FAILED",
        "failure_message": "3DS challenge not completed by customer.",
        "attempt_count": 1, "customer_locale": "hi-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(10), "last_attempt_at": h(10),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_AF005", "customer_id": "cust_405", "customer_name": "Vandana Rao",
        "amount": 27500.0, "currency": "INR", "payment_method": "card",
        "failure_category": "authentication_failed", "failure_code": "3DS_FAILED",
        "failure_message": "High-value 3DS failure. Escalated for review.",
        "attempt_count": 1, "customer_locale": "te-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(9), "last_attempt_at": h(9),
        "hidden_recovery_outcome": "escalated",  # > 25000
    },
    {
        "payment_id": "pay_AF006", "customer_id": "cust_406", "customer_name": "Harish Kulkarni",
        "amount": 900.0, "currency": "INR", "payment_method": "upi",
        "failure_category": "authentication_failed", "failure_code": "UPI_PIN_FAILED",
        "failure_message": "UPI PIN failed. Customer needs to retry.",
        "attempt_count": 1, "customer_locale": "kn-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(5), "last_attempt_at": h(5),
        "hidden_recovery_outcome": "needs_customer_action",
    },
    {
        "payment_id": "pay_AF007", "customer_id": "cust_407", "customer_name": "Neha Bhatt",
        "amount": 4500.0, "currency": "INR", "payment_method": "card",
        "failure_category": "authentication_failed", "failure_code": "OTP_FAILED",
        "failure_message": "OTP not received or expired.",
        "attempt_count": 1, "customer_locale": "mr-IN", "consent_for_voice": False, "opted_out": True,
        "created_at": h(7), "last_attempt_at": h(7),
        "hidden_recovery_outcome": "not_recovered",  # opted out
    },
    {
        "payment_id": "pay_AF008", "customer_id": "cust_408", "customer_name": "Arun Krishnan",
        "amount": 2100.0, "currency": "INR", "payment_method": "card",
        "failure_category": "authentication_failed", "failure_code": "3DS_FAILED",
        "failure_message": "3DS auth timeout.",
        "attempt_count": 2, "customer_locale": "ta-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(20), "last_attempt_at": h(9),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_AF009", "customer_id": "cust_409", "customer_name": "Swati Bansal",
        "amount": 6700.0, "currency": "INR", "payment_method": "card",
        "failure_category": "authentication_failed", "failure_code": "OTP_FAILED",
        "failure_message": "OTP failed multiple times.",
        "attempt_count": 1, "customer_locale": "hi-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(12), "last_attempt_at": h(12),
        "hidden_recovery_outcome": "not_recovered",
    },

    # ── CHECKOUT ABANDONED (7) ───────────────────────────────────────────
    {
        "payment_id": "pay_CA001", "customer_id": "cust_501", "customer_name": "Mohit Aggarwal",
        "amount": 1999.0, "currency": "INR", "payment_method": "card",
        "failure_category": "checkout_abandoned", "failure_code": "USER_DROPPED_OFF",
        "failure_message": "User left checkout page before completing payment.",
        "attempt_count": 1, "customer_locale": "hi-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(5), "last_attempt_at": h(5),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_CA002", "customer_id": "cust_502", "customer_name": "Tanya Malhotra",
        "amount": 3499.0, "currency": "INR", "payment_method": "upi",
        "failure_category": "checkout_abandoned", "failure_code": "SESSION_EXPIRED",
        "failure_message": "Payment session expired after inactivity.",
        "attempt_count": 1, "customer_locale": "en-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(8), "last_attempt_at": h(8),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_CA003", "customer_id": "cust_503", "customer_name": "Sanjay Dubey",
        "amount": 22000.0, "currency": "INR", "payment_method": "netbanking",
        "failure_category": "checkout_abandoned", "failure_code": "USER_DROPPED_OFF",
        "failure_message": "High-value checkout abandoned.",
        "attempt_count": 1, "customer_locale": "hi-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(14), "last_attempt_at": h(14),
        "hidden_recovery_outcome": "not_recovered",
    },
    {
        "payment_id": "pay_CA004", "customer_id": "cust_504", "customer_name": "Isha Mathur",
        "amount": 850.0, "currency": "INR", "payment_method": "card",
        "failure_category": "checkout_abandoned", "failure_code": "SESSION_EXPIRED",
        "failure_message": "Session expired on checkout.",
        "attempt_count": 1, "customer_locale": "en-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(6), "last_attempt_at": h(6),
        "hidden_recovery_outcome": "not_recovered",
    },
    {
        "payment_id": "pay_CA005", "customer_id": "cust_505", "customer_name": "Vishal Tandon",
        "amount": 4800.0, "currency": "INR", "payment_method": "card",
        "failure_category": "checkout_abandoned", "failure_code": "USER_DROPPED_OFF",
        "failure_message": "Customer dropped off at payment page.",
        "attempt_count": 1, "customer_locale": "en-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(10), "last_attempt_at": h(10),
        "hidden_recovery_outcome": "not_recovered",
    },
    {
        "payment_id": "pay_CA006", "customer_id": "cust_506", "customer_name": "Padma Subramaniam",
        "amount": 2800.0, "currency": "INR", "payment_method": "upi",
        "failure_category": "checkout_abandoned", "failure_code": "SESSION_EXPIRED",
        "failure_message": "UPI session expired.",
        "attempt_count": 1, "customer_locale": "ta-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(16), "last_attempt_at": h(13),
        "hidden_recovery_outcome": "unresolved",
    },
    {
        "payment_id": "pay_CA007", "customer_id": "cust_507", "customer_name": "Ashish Ghosh",
        "amount": 1350.0, "currency": "INR", "payment_method": "card",
        "failure_category": "checkout_abandoned", "failure_code": "USER_DROPPED_OFF",
        "failure_message": "User abandoned checkout mid-way.",
        "attempt_count": 1, "customer_locale": "bn-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(11), "last_attempt_at": h(11),
        "hidden_recovery_outcome": "unresolved",
    },

    # ── SUBSCRIPTION FAILED (5) ──────────────────────────────────────────
    {
        "payment_id": "pay_SF001", "customer_id": "cust_601", "customer_name": "Geeta Krishnaswamy",
        "amount": 999.0, "currency": "INR", "payment_method": "card",
        "failure_category": "subscription_failed", "failure_code": "MANDATE_FAILED",
        "failure_message": "Auto-debit mandate failed. Bank did not approve.",
        "attempt_count": 1, "customer_locale": "ta-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(24), "last_attempt_at": h(20),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_SF002", "customer_id": "cust_602", "customer_name": "Dinesh Pathak",
        "amount": 4999.0, "currency": "INR", "payment_method": "card",
        "failure_category": "subscription_failed", "failure_code": "RECURRING_DECLINED",
        "failure_message": "Recurring payment declined by bank.",
        "attempt_count": 2, "customer_locale": "hi-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(30), "last_attempt_at": h(16),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_SF003", "customer_id": "cust_603", "customer_name": "Uma Krishnan",
        "amount": 1499.0, "currency": "INR", "payment_method": "card",
        "failure_category": "subscription_failed", "failure_code": "MANDATE_FAILED",
        "failure_message": "Mandate failed. Max retries exhausted.",
        "attempt_count": 3, "customer_locale": "ta-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(40), "last_attempt_at": h(10),
        "hidden_recovery_outcome": "not_recovered",  # max retries
    },
    {
        "payment_id": "pay_SF004", "customer_id": "cust_604", "customer_name": "Brijesh Tripathi",
        "amount": 2000.0, "currency": "INR", "payment_method": "card",
        "failure_category": "subscription_failed", "failure_code": "RECURRING_DECLINED",
        "failure_message": "Recurring payment declined.",
        "attempt_count": 1, "customer_locale": "hi-IN", "consent_for_voice": True, "opted_out": False,
        "created_at": h(15), "last_attempt_at": h(9),
        "hidden_recovery_outcome": "recovered",
    },
    {
        "payment_id": "pay_SF005", "customer_id": "cust_605", "customer_name": "Lalitha Subramanian",
        "amount": 799.0, "currency": "INR", "payment_method": "card",
        "failure_category": "subscription_failed", "failure_code": "MANDATE_FAILED",
        "failure_message": "Mandate not registered properly.",
        "attempt_count": 1, "customer_locale": "ta-IN", "consent_for_voice": False, "opted_out": False,
        "created_at": h(22), "last_attempt_at": h(18),
        "hidden_recovery_outcome": "not_recovered",
    },
]


def get_seed_payments():
    return PAYMENTS_SEED
